name: otaku_fix
description: An open source Manga reader made with Flutter.

publish_to:

version: 0.9.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  persistent_bottom_nav_bar: ^4.0.2
  http: ^0.13.3
  html: ^0.15.0
  cached_network_image: ^3.1.0
  path_provider: ^2.0.2
  photo_view: ^0.12.0
  sqflite: ^2.0.0+4
  path: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          style: normal
        - asset: assets/fonts/Montserrat-Semibold.ttf


