name: otaku_fix
description: A new Flutter application.


publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  persistent_bottom_nav_bar: any
  http: ^0.12.2
  html: ^0.14.0+4
  floating_search_bar: ^0.3.0
  cached_network_image: ^2.3.3
  path_provider: ^1.6.21
  photo_view: ^0.10.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          style: normal
        - asset: assets/fonts/Montserrat-Semibold.ttf


